config/routes.rb
#routeを設定するための関数（あんま気にしなくていい？）
Rails.application.routes.draw do
  #ユーザー認証関係のURLを自動生成
  devise_for :users

  #ログアウトの際,GETメソッドではなくDELETEメソッドをリクエストするためのコード
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  #indexページの表示
  get 'memos', to: 'memos#index' , as: 'memos'

  get "up" => "rails/health#show", as: :rails_health_check
  #CSV読み込みページ
  get 'user/:id', to: 'memos#users' , as: 'userpage'
  #それぞれのジャンルのページ
  get "notes" => 'memos#notes'
  get "chord" => 'memos#chord'
  get "peak" => 'memos#peak'
  get "charge" => 'memos#charge'
  get "scratch" => 'memos#scratch'
  get "soflan" => 'memos#soflan'
  #ホームページ
  root 'memos#home'

  #memosの関数として:index, :update, :destroy, :createなどを設定
  resources :memos do
    #importクラスとdestroy_allクラスを追加
    collection do
      post :import
      delete :destroy_all
    end
  end

end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :raderval
  #importメソッド
def self.import(file, resource)
  begin
    #user_idを取得
    user = resource
    #Radervalテーブルのデータを変数に格納
    titles = Raderval.pluck(:title)
    ids = Raderval.pluck(:id)
    maxscores = Raderval.pluck(:maxscore)
    a1 = Raderval.pluck(:notesval)
    a2 = Raderval.pluck(:chordval)
    a3 = Raderval.pluck(:peakval)
    a4 = Raderval.pluck(:chargeval)
    a5 = Raderval.pluck(:scratchval)
    a6 = Raderval.pluck(:soflanval)
    l_maxscores = Raderval.pluck(:l_maxscore)
    l1 = Raderval.pluck(:l_notesval)
    l2 = Raderval.pluck(:l_chordval)
    l3 = Raderval.pluck(:l_peakval)
    l4 = Raderval.pluck(:l_chargeval)
    l5 = Raderval.pluck(:l_scratchval)
    l6 = Raderval.pluck(:l_soflanval)

    CSV.foreach(file.path, headers: true, liberal_parsing: true) do |row|
      if titles.include?(row["タイトル"])
        index = titles.index(row["タイトル"])
        if row["ANOTHER スコア"]  != "0" 
          data = find_by(title: row["タイトル"], user_id:user,  difficulty:"A") || new  
          data.title = row["タイトル"]
          data.raderval_id = ids[index]
          data.difficulty = "A"
          data.user_id = user
          data.exscore = row["ANOTHER スコア"].to_i 
          aaa =  (Float(row["ANOTHER スコア"]) / Float(maxscores[index])) * Float(a1[index])
          data.notes = (aaa * 100).floor / 100.0
          aaa =  (Float(row["ANOTHER スコア"]) / Float(maxscores[index])) * Float(a2[index])
          data.chord = (aaa * 100).floor / 100.0
          aaa =  (Float(row["ANOTHER スコア"]) / Float(maxscores[index])) * Float(a3[index])
          data.peak = (aaa * 100).floor / 100.0
          aaa =  (Float(row["ANOTHER スコア"]) / Float(maxscores[index])) * Float(a4[index])
          data.charge = (aaa * 100).floor / 100.0
          aaa =  (Float(row["ANOTHER スコア"]) / Float(maxscores[index])) * Float(a5[index])
          data.scratch = (aaa * 100).floor / 100.0
          aaa =  (Float(row["ANOTHER スコア"]) / Float(maxscores[index])) * Float(a6[index])
          data.soflan = (aaa * 100).floor / 100.0
          data.notes_growth_rate   = Float(1 / Float(maxscores[index]) * Float(a1[index]))
          data.chord_growth_rate   = Float(1 / Float(maxscores[index]) * Float(a2[index]))
          data.peak_growth_rate    = Float(1 / Float(maxscores[index]) * Float(a3[index]))
          data.charge_growth_rate  = Float(1 / Float(maxscores[index]) * Float(a4[index]))
          data.scratch_growth_rate = Float(1 / Float(maxscores[index]) * Float(a5[index]))
          data.soflan_growth_rate  = Float(1 / Float(maxscores[index]) * Float(a6[index]))
          data.save
        end

        if row["LEGGENDARIA スコア"]  != "0" 
          data = find_by(title: row["タイトル"], user_id:user, difficulty:"L") || new  
          data.title = row["タイトル"]
          data.raderval_id = ids[index]
          data.difficulty = "L"
          data.user_id = user
          data.exscore = row["LEGGENDARIA スコア"].to_i 
          aaa =  (Float(row["LEGGENDARIA スコア"]) / Float(l_maxscores[index])) * Float(l1[index])
          data.notes = (aaa * 100).floor / 100.0
          aaa =  (Float(row["LEGGENDARIA スコア"]) / Float(l_maxscores[index])) * Float(l2[index])
          data.chord = (aaa * 100).floor / 100.0
          aaa =  (Float(row["LEGGENDARIA スコア"]) / Float(l_maxscores[index])) * Float(l3[index])
          data.peak = (aaa * 100).floor / 100.0
          aaa =  (Float(row["LEGGENDARIA スコア"]) / Float(l_maxscores[index])) * Float(l4[index])
          data.charge = (aaa * 100).floor / 100.0
          aaa =  (Float(row["LEGGENDARIA スコア"]) / Float(l_maxscores[index])) * Float(l5[index])
          data.scratch = (aaa * 100).floor / 100.0
          aaa =  (Float(row["LEGGENDARIA スコア"]) / Float(l_maxscores[index])) * Float(l6[index])
          data.soflan = (aaa * 100).floor / 100.0
          data.notes_growth_rate   = Float(1 / Float(maxscores[index]) * Float(l1[index]))
          data.chord_growth_rate   = Float(1 / Float(maxscores[index]) * Float(l2[index]))
          data.peak_growth_rate    = Float(1 / Float(maxscores[index]) * Float(l3[index]))
          data.charge_growth_rate  = Float(1 / Float(maxscores[index]) * Float(l4[index]))
          data.scratch_growth_rate = Float(1 / Float(maxscores[index]) * Float(l5[index]))
          data.soflan_growth_rate  = Float(1 / Float(maxscores[index]) * Float(l6[index]))
          data.save
        end

      end
    end 
  rescue CSV::MalformedCSVError => e
    Rails.logger.error "CSV ファイルの形式が不正です: #{e.message}"
    # エラー処理: 例) エラー内容を通知するなど
    false
  rescue StandardError => e
    Rails.logger.error "予期しないエラーが発生しました: #{e.message}"
    # エラー処理: 例) エラー内容を通知するなど
    false
  end
end

end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def index
    if user_signed_in? 
      #orderによって、param[:sort]で指定された条件で結果をソートして、ソートされた結果を@memos変数に格納
      @resource = current_user.id
      @memos = Memo.where(user_id: current_user.id).joins(:raderval).select('memos.*, radervals.*').order(params[:sort]).order('notes')
      #memos = Memo.joins(:raderval).select('memos.*, radervals.*').order(params[:sort])
    end
    
  end

  def users
  end

  def notes
    @resource = current_user.id
    @memos = Memo.where(user_id: current_user.id).joins(:raderval).select('memos.*, radervals.*').order(params[:sort]).order('notes')
    #memos = Memo.joins(:raderval).select('memos.*, radervals.*').order(params[:sort])
  end

  def chord
    @resource = current_user.id
    @memos = Memo.where(user_id: current_user.id).joins(:raderval).select('memos.*, radervals.*').order(params[:sort]).order('chord')
    #memos = Memo.joins(:raderval).select('memos.*, radervals.*').order(params[:sort])
  end
  
  def peak
    @resource = current_user.id
    @memos = Memo.where(user_id: current_user.id).joins(:raderval).select('memos.*, radervals.*').order(params[:sort]).order('peak')
    #memos = Memo.joins(:raderval).select('memos.*, radervals.*').order(params[:sort])
  end

  def charge
    @resource = current_user.id
    @memos = Memo.where(user_id: current_user.id).joins(:raderval).select('memos.*, radervals.*').order(params[:sort]).order('charge')
    #memos = Memo.joins(:raderval).select('memos.*, radervals.*').order(params[:sort])
  end

  def scratch
    @resource = current_user.id
    @memos = Memo.where(user_id: current_user.id).joins(:raderval).select('memos.*, radervals.*').order(params[:sort]).order('scratch')
    #memos = Memo.joins(:raderval).select('memos.*, radervals.*').order(params[:sort])
  end

  def soflan
    @resource = current_user.id
    @memos = Memo.where(user_id: current_user.id).joins(:raderval).select('memos.*, radervals.*').order(params[:sort]).order('soflan')
    #memos = Memo.joins(:raderval).select('memos.*, radervals.*').order(params[:sort])
  end
 
  def create
    @memo_new = Memo.new(memos_params)
    @memo_new.save
    redirect_to memos_path, notice: 'Memo was successfully created.'
  end

  def destroy_all
    Memo.destroy_all
    redirect_to memos_path, notice: 'All Memos were successfully deleted.'
  end
 
  def update
    @memo = Memo.find(params[:id])
    @memo.update(memos_params)
    redirect_to memos_path, notice: 'Memo was successfully updated.'
  end
 
  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy
    redirect_to memos_path, notice: 'Memo was successfully deleted.'
  end

  def import
    resource = current_user.id
    Memo.import(params[:file], resource)
    redirect_to memos_path, notice: 'Import was successfully created.'
  end 
  private
 
  def memos_params
    params.require(:memo).permit(:title, :description)
  end



end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/charge.html.erb
<% if user_signed_in? %>

<div class="wrapper">
  <div class="container flex-start">
    
    <div class="col-box-1">
      <button type="button" class="btn btn-primary">
        <%= link_to 'CSVアップロードページへ', userpage_path(@resource), class: "btn" %>
      </button>   
    </div>

    <div class="col-box-1">
			<h4>↓ジャンルごとにソート↓</h4>
      <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
        <a href="<%= notes_path %>" class="btn btn-outline-primary">NOTES</a>
        <a href="<%= chord_path %>" class="btn btn-outline-primary">CHORD</a>
        <a href="<%= peak_path %>" class="btn btn-outline-primary">PEAK</a>
        <a href="<%= charge_path %>" class="btn btn-outline-primary">CHARGE</a>
        <a href="<%= scratch_path %>" class="btn btn-outline-primary">SCRATCH</a>
        <a href="<%= soflan_path %>" class="btn btn-outline-primary">SOF-LAN</a>
      </div>
    </div>

    <% ave = 0 %>
    <% @memos.reverse.take(10).each do |song| %>
      <% ave += song.charge %>
    <% end %>
    <%= image_tag 'CHARGE.png', alt: 'Example Image', class: 'my-image', width: 120, height: 60 %>
    <h1><%= '%.2f' % ((ave*100).floor / 1000.0)%></h1>	
  
    <table class="table table-striped-columns">
      <thead>
      	<tr class="table table-dark table-striped">
  		  	<th>曲名</th>
					<th>難易度</th>          
          <th>レーダー値(CHARGE)</th>
          <th>EXスコア</th>           
          <th>1点伸びた時の上昇値</th>               
        </tr>
      </thead>
      <tbody>
        <% @memos.reverse.take(10).each do |song| %>
          <tr>
            <td class="table-warning"><%= song.title%></td>						
            <td class="table-warning"><%= song.difficulty%></td>
            <td class="table-warning"><%= '%.2f' % song.charge%></td>
            <td class="table-warning"><%= song.exscore%></td>            
            <td class="table-warning"><%= song.charge_growth_rate.round(2)%></td>
          </tr>       
        <% end %>

				<% @memos.reverse.drop(10).each do |song| %>
          <tr>
            <td><%= song.title%></td>						
            <td><%= song.difficulty%></td>
            <td><%= '%.2f' % song.charge%></td>
            <td><%= song.exscore%></td>
            <td><%= song.charge_growth_rate.round(2)%></td>            
          </tr>       
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% else %>
	<div class="alert alert-danger" role="alert">
  <h2>サインインをしてください</h2>
  </div>
  <div class="container flex-start">
    <div class="col-box-1">
    <button type="button" class="btn btn-outline-primary">
      <%= link_to '新規登録', new_user_registration_path, method: :get , class: "btn"%>
    </button>
    <button type="button" class="btn btn-outline-primary">
      <%= link_to 'ログイン', new_user_session_path, method: :get , class: "btn"%>
    </button>
  </div>
<% end %>

app/views/memos/chord.html.erb
<% if user_signed_in? %>

<div class="wrapper">
  <div class="container flex-start">
    
    <div class="col-box-1">
      <button type="button" class="btn btn-primary">
        <%= link_to 'CSVアップロードページへ', userpage_path(@resource), class: "btn" %>
      </button>   
    </div>

    <div class="col-box-1">
			<h4>↓ジャンルごとにソート↓</h4>
      <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
        <a href="<%= notes_path %>" class="btn btn-outline-primary">NOTES</a>
        <a href="<%= chord_path %>" class="btn btn-outline-primary">CHORD</a>
        <a href="<%= peak_path %>" class="btn btn-outline-primary">PEAK</a>
        <a href="<%= charge_path %>" class="btn btn-outline-primary">CHARGE</a>
        <a href="<%= scratch_path %>" class="btn btn-outline-primary">SCRATCH</a>
        <a href="<%= soflan_path %>" class="btn btn-outline-primary">SOF-LAN</a>
      </div>
    </div>

    <% ave = 0 %>
    <% @memos.reverse.take(10).each do |song| %>
      <% ave += song.chord %>
    <% end %>
    <%= image_tag 'CHORD.png', alt: 'Example Image', class: 'my-image', width: 120, height: 60 %>
    <h1><%= '%.2f' % ((ave*100).floor / 1000.0)%></h1>	
  
    <table class="table table-striped-columns">
      <thead>
      	<tr class="table table-dark table-striped">
  		  	<th>曲名</th>
					<th>難易度</th>          
          <th>レーダー値(CHORD)</th>
          <th>EXスコア</th>           
          <th>1点伸びた時の上昇値</th>               
        </tr>
      </thead>
      <tbody>
        <% @memos.reverse.take(10).each do |song| %>
          <tr>
            <td class="table-warning"><%= song.title%></td>						
            <td class="table-warning"><%= song.difficulty%></td>
            <td class="table-warning"><%='%.2f' % song.chord%></td>
            <td class="table-warning"><%= song.exscore%></td>            
            <td class="table-warning"><%= song.chord_growth_rate.round(2)%></td>
          </tr>       
        <% end %>

				<% @memos.reverse.drop(10).each do |song| %>
          <tr>
            <td><%= song.title%></td>						
            <td><%= song.difficulty%></td>
            <td><%= '%.2f' % song.chord%></td>
            <td><%= song.exscore%></td>
            <td><%= song.chord_growth_rate.round(2)%></td>            
          </tr>       
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% else %>
	<div class="alert alert-danger" role="alert">
  <h2>サインインをしてください</h2>
  </div>
  <div class="container flex-start">
    <div class="col-box-1">
    <button type="button" class="btn btn-outline-primary">
      <%= link_to '新規登録', new_user_registration_path, method: :get , class: "btn"%>
    </button>
    <button type="button" class="btn btn-outline-primary">
      <%= link_to 'ログイン', new_user_session_path, method: :get , class: "btn"%>
    </button>
  </div>
<% end %>

app/views/memos/index.html.erb
<% if user_signed_in? %>

<div class="wrapper">
  <div class="container flex-start">
    
    <div class="col-box-1">
      <button type="button" class="btn btn-primary">
        <%= link_to 'CSVアップロードページへ', userpage_path(@resource), class: "btn" %>
      </button>   
    </div>

    <div class="col-box-1">
			<h4>↓ジャンルごとにソート↓</h4>
      <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
        <a href="<%= notes_path %>" class="btn btn-outline-primary">NOTES</a>
        <a href="<%= chord_path %>" class="btn btn-outline-primary">CHORD</a>
        <a href="<%= peak_path %>" class="btn btn-outline-primary">PEAK</a>
        <a href="<%= charge_path %>" class="btn btn-outline-primary">CHARGE</a>
        <a href="<%= scratch_path %>" class="btn btn-outline-primary">SCRATCH</a>
        <a href="<%= soflan_path %>" class="btn btn-outline-primary">SOF-LAN</a>
      </div>
    </div>
  </div>
</div>

<% else %>
	<div class="alert alert-danger" role="alert">
  <h2>サインインをしてください</h2>
  </div>
  <div class="container flex-start">
    <div class="col-box-1">
    <button type="button" class="btn btn-outline-primary">
      <%= link_to '新規登録', new_user_registration_path, method: :get , class: "btn"%>
    </button>
    <button type="button" class="btn btn-outline-primary">
      <%= link_to 'ログイン', new_user_session_path, method: :get , class: "btn"%>
    </button>
  </div>
<% end %>

app/views/memos/notes.html.erb
<% if user_signed_in? %>

<div class="wrapper">
  <div class="container flex-start">
    
    <div class="col-box-1">
      <button type="button" class="btn btn-primary">
        <%= link_to 'CSVアップロードページへ', userpage_path(@resource), class: "btn" %>
      </button>   
    </div>

    <div class="col-box-1">
			<h4>↓ジャンルごとにソート↓</h4>
      <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
        <a href="<%= notes_path %>" class="btn btn-outline-primary">NOTES</a>
        <a href="<%= chord_path %>" class="btn btn-outline-primary">CHORD</a>
        <a href="<%= peak_path %>" class="btn btn-outline-primary">PEAK</a>
        <a href="<%= charge_path %>" class="btn btn-outline-primary">CHARGE</a>
        <a href="<%= scratch_path %>" class="btn btn-outline-primary">SCRATCH</a>
        <a href="<%= soflan_path %>" class="btn btn-outline-primary">SOF-LAN</a>
      </div>
    </div>

    <% ave = 0 %>
    <% @memos.reverse.take(10).each do |song| %>
      <% ave += song.notes %>
    <% end %>
    <%= image_tag 'NOTES.png', alt: 'Example Image', class: 'my-image', width: 120, height: 60 %>
    <h1><%= '%.2f' % ((ave*100).floor / 1000.0)%></h1>	

    <table class="table table-striped-columns">
      <thead>
      	<tr class="table table-dark table-striped">
  		  	<th>曲名</th>
					<th>難易度</th>          
          <th>レーダー値(NOTES)</th>
          <th>EXスコア</th>           
          <th>1点伸びた時の上昇値</th>               
        </tr>
      </thead>
      <tbody>
        <% @memos.reverse.take(10).each do |song| %>
          <tr>
            <td class="table-warning"><%= song.title%></td>						
            <td class="table-warning"><%= song.difficulty%></td>
            <td class="table-warning"><%= '%.2f' % song.notes%></td>
            <td class="table-warning"><%= song.exscore%></td>            
            <td class="table-warning"><%= song.notes_growth_rate.round(2)%></td>
          </tr>       
        <% end %>

				<% @memos.reverse.drop(10).each do |song| %>
          <tr>
            <td><%= song.title%></td>						
            <td><%= song.difficulty%></td>
            <td><%= '%.2f' % song.notes%></td>
            <td><%= song.exscore%></td>
            <td><%= song.notes_growth_rate.round(2)%></td>            
          </tr>       
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% else %>
	<div class="alert alert-danger" role="alert">
  <h2>サインインをしてください</h2>
  </div>
  <div class="container flex-start">
    <div class="col-box-1">
    <button type="button" class="btn btn-outline-primary">
      <%= link_to '新規登録', new_user_registration_path, method: :get , class: "btn"%>
    </button>
    <button type="button" class="btn btn-outline-primary">
      <%= link_to 'ログイン', new_user_session_path, method: :get , class: "btn"%>
    </button>
  </div>
<% end %>

app/views/memos/peak.html.erb
<% if user_signed_in? %>

<div class="wrapper">
  <div class="container flex-start">
    
    <div class="col-box-1">
      <button type="button" class="btn btn-primary">
        <%= link_to 'CSVアップロードページへ', userpage_path(@resource), class: "btn" %>
      </button>   
    </div>

    <div class="col-box-1">
			<h4>↓ジャンルごとにソート↓</h4>
      <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
        <a href="<%= notes_path %>" class="btn btn-outline-primary">NOTES</a>
        <a href="<%= chord_path %>" class="btn btn-outline-primary">CHORD</a>
        <a href="<%= peak_path %>" class="btn btn-outline-primary">PEAK</a>
        <a href="<%= charge_path %>" class="btn btn-outline-primary">CHARGE</a>
        <a href="<%= scratch_path %>" class="btn btn-outline-primary">SCRATCH</a>
        <a href="<%= soflan_path %>" class="btn btn-outline-primary">SOF-LAN</a>
      </div>
    </div>

    <% ave = 0 %>
    <% @memos.reverse.take(10).each do |song| %>
      <% ave += song.peak %>
    <% end %>
    <%= image_tag 'PEAK.png', alt: 'Example Image', class: 'my-image', width: 120, height: 60 %>

    <h1><%= '%.2f' % ((ave*100).floor / 1000.0)%></h1>	
  
    <table class="table table-striped-columns">
      <thead>
      	<tr class="table table-dark table-striped">
  		  	<th>曲名</th>
					<th>難易度</th>          
          <th>レーダー値(PEAK)</th>
          <th>EXスコア</th>           
          <th>1点伸びた時の上昇値</th>               
        </tr>
      </thead>
      <tbody>
        <% @memos.reverse.take(10).each do |song| %>
          <tr>
            <td class="table-warning"><%= song.title%></td>						
            <td class="table-warning"><%= song.difficulty%></td>
            <td class="table-warning"><%= '%.2f' % song.peak%></td>
            <td class="table-warning"><%= song.exscore%></td>            
            <td class="table-warning"><%= song.peak_growth_rate.round(2)%></td>
          </tr>       
        <% end %>

				<% @memos.reverse.drop(10).each do |song| %>
          <tr>
            <td><%= song.title%></td>						
            <td><%= song.difficulty%></td>
            <td><%= '%.2f' % song.peak%></td>
            <td><%= song.exscore%></td>
            <td><%= song.peak_growth_rate.round(2)%></td>            
          </tr>       
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% else %>
	<div class="alert alert-danger" role="alert">
  <h2>サインインをしてください</h2>
  </div>
  <div class="container flex-start">
    <div class="col-box-1">
    <button type="button" class="btn btn-outline-primary">
      <%= link_to '新規登録', new_user_registration_path, method: :get , class: "btn"%>
    </button>
    <button type="button" class="btn btn-outline-primary">
      <%= link_to 'ログイン', new_user_session_path, method: :get , class: "btn"%>
    </button>
  </div>
<% end %>

app/views/memos/scratch.html.erb
<% if user_signed_in? %>

<div class="wrapper">
  <div class="container flex-start">
    
    <div class="col-box-1">
      <button type="button" class="btn btn-primary">
        <%= link_to 'CSVアップロードページへ', userpage_path(@resource), class: "btn" %>
      </button>   
    </div>

    <div class="col-box-1">
			<h4>↓ジャンルごとにソート↓</h4>
      <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
        <a href="<%= notes_path %>" class="btn btn-outline-primary">NOTES</a>
        <a href="<%= chord_path %>" class="btn btn-outline-primary">CHORD</a>
        <a href="<%= peak_path %>" class="btn btn-outline-primary">PEAK</a>
        <a href="<%= charge_path %>" class="btn btn-outline-primary">CHARGE</a>
        <a href="<%= scratch_path %>" class="btn btn-outline-primary">SCRATCH</a>
        <a href="<%= soflan_path %>" class="btn btn-outline-primary">SOF-LAN</a>
      </div>
    </div>

    <% ave = 0 %>
    <% @memos.reverse.take(10).each do |song| %>
      <% ave += song.scratch %>
    <% end %>
    <%= image_tag 'SCRATCH.png', alt: 'Example Image', class: 'my-image', width: 120, height: 60 %>
    <h1><%= '%.2f' % ((ave*100).floor / 1000.0)%></h1>	
  
    <table class="table table-striped-columns">
      <thead>
      	<tr class="table table-dark table-striped">
  		  	<th>曲名</th>
					<th>難易度</th>          
          <th>レーダー値(SCRATCH)</th>
          <th>EXスコア</th>           
          <th>1点伸びた時の上昇値</th>               
        </tr>
      </thead>
      <tbody>
        <% @memos.reverse.take(10).each do |song| %>
          <tr>
            <td class="table-warning"><%= song.title%></td>						
            <td class="table-warning"><%= song.difficulty%></td>
            <td class="table-warning"><%= '%.2f' % song.scratch%></td>
            <td class="table-warning"><%= song.exscore%></td>            
            <td class="table-warning"><%= song.scratch_growth_rate.round(2)%></td>
          </tr>       
        <% end %>

				<% @memos.reverse.drop(10).each do |song| %>
          <tr>
            <td><%= song.title%></td>						
            <td><%= song.difficulty%></td>
            <td><%= '%.2f' % song.scratch%></td>
            <td><%= song.exscore%></td>
            <td><%= song.scratch_growth_rate.round(2)%></td>            
          </tr>       
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% else %>
	<div class="alert alert-danger" role="alert">
  <h2>サインインをしてください</h2>
  </div>
  <div class="container flex-start">
    <div class="col-box-1">
    <button type="button" class="btn btn-outline-primary">
      <%= link_to '新規登録', new_user_registration_path, method: :get , class: "btn"%>
    </button>
    <button type="button" class="btn btn-outline-primary">
      <%= link_to 'ログイン', new_user_session_path, method: :get , class: "btn"%>
    </button>
  </div>
<% end %>

app/views/memos/userpage.erb
<%= form_tag import_memos_path, multipart: true do %>

  <%= file_field_tag :file, class:"form-control" %>
  <%= submit_tag "アップロード", class:"btn btn-secondary"%>

<% end %>

<%#= link_to 'ログアウト', destroy_user_session_path, method: :delete %>

app/views/memos/users.erb
<% if user_signed_in? %>

<%= form_tag import_memos_path, multipart:true do %>

  <%= file_field_tag :file, class:"form-control", accept:".csv" %>
  <%= submit_tag "アップロード", class:"btn btn-secondary"%>

<% end %>

<%#= link_to 'ログアウト', destroy_user_session_path, method: :delete %>


<div class="col-box-1">
  <button type="button" class="btn btn-primary">
    <%= link_to 'スコア一覧へ', memos_path, class: "btn" %>
  </button>   
</div>

<%= current_user.id %>

<% else %>
	<div class="alert alert-danger" role="alert">
  <h2>サインインをしてください</h2>
  </div>
  <div class="container flex-start">
    <div class="col-box-1">
    <button type="button" class="btn btn-outline-primary">
      <%= link_to '新規登録', new_user_registration_path, method: :get , class: "btn"%>
    </button>
    <button type="button" class="btn btn-outline-primary">
      <%= link_to 'ログイン', new_user_session_path, method: :get , class: "btn"%>
    </button>
  </div>
<% end %>
